name: 'Build and Package'

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt

      - run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}-${{ matrix.os }}-${{ github.sha }}
          path: dist/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - working-directory: artifacts
        run: find . -name "*.whl"